### ISSUE TITLE
Implement linear model variants

### ISSUE THREAD

**Issue by p-gw** [JuliaPsychometrics/RaschModels.jl#17]
This issue splits #5.

Separately implement linear variants of simple Rasch models: 

## TODO
- [ ] Linear Logistic Test Model
- [ ] Linear Rating Scale Model
- [ ] Linear Partial Credit Model
